# Generated by Django 4.2.6 on 2023-10-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_bannervideo_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannervideo',
            name='video_file',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
