# Generated by Django 4.2.6 on 2023-10-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_menuitem_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/')),
            ],
            options={
                'verbose_name': 'Video Banner',
            },
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name_plural': 'Menu'},
        ),
    ]
