# Generated by Django 4.2.6 on 2023-10-05 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bannervideo_alter_menuitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannervideo',
            options={'verbose_name_plural': 'Video Banner'},
        ),
        migrations.RemoveField(
            model_name='bannervideo',
            name='video_file',
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/')),
                ('banner_video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.bannervideo')),
            ],
        ),
    ]
