# Generated by Django 4.2.6 on 2023-10-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_bannervideo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videofile',
            name='video_file',
        ),
        migrations.AddField(
            model_name='bannervideo',
            name='video_file',
            field=models.FileField(default='', upload_to='videos/'),
            preserve_default=False,
        ),
    ]
