# Generated by Django 4.2.6 on 2023-10-11 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_service_itens_delete_videofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='image_cropped',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/cropped/'),
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.bannervideo')),
            ],
        ),
    ]
