# Generated by Django 4.2.6 on 2023-10-11 22:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_galleryimage_image_cropped_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannervideo',
            name='video_file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
