# Generated by Django 4.2.6 on 2023-10-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('instagram', models.URLField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name_plural': 'Portfolio'},
        ),
    ]
