# Generated by Django 4.2.6 on 2023-10-05 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_footeritems_alter_galleryimage_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FooterItems',
            new_name='FooterItem',
        ),
    ]
