# Generated by Django 4.2.6 on 2023-10-05 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_about_item_alter_footeritem_options_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='titulo',
        ),
    ]
