# Generated by Django 4.2.6 on 2023-10-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_about_options_footeritem_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='', upload_to='service/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='youtube_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
