# Generated by Django 4.2.6 on 2023-10-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_service_image_service_youtube_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Services Items'},
        ),
        migrations.AlterField(
            model_name='service',
            name='itens',
            field=models.ManyToManyField(blank=True, null=True, to='app.item'),
        ),
    ]
