# Generated by Django 4.2.6 on 2023-10-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_item_options_alter_service_itens'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='titulo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
