# Generated by Django 4.2.6 on 2023-10-06 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_contato'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contato',
            new_name='Contact',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Emails received'},
        ),
        migrations.AlterModelOptions(
            name='footeritem',
            options={'verbose_name_plural': 'Contact area'},
        ),
    ]
