# Generated by Django 4.2.6 on 2023-10-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_contato_contact_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='images_per_load',
            field=models.IntegerField(default=5),
        ),
    ]
