# Generated by Django 4.2.6 on 2023-10-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_galleryimage_images_per_load'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='images_per_load',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image_cropped',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/cropped/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='service/', verbose_name='Capa do vídeo'),
        ),
    ]
